MERGE 
	`<INSERT_PROJECT_ID>.<INSERT_DATASET_NAME>.<INSERT_PLAY_ID_NOTES_TABLE_NAME>` AS A 
USING 
	(SELECT "<INSERT_PLAY_ID_HERE>" AS Play_Id, "<INSERT_NOTE_HERE>" AS Note, CURRENT_TIMESTAMP() AS Last_Update) AS B 
ON 
	A.Play_Id = B.Play_Id 
WHEN NOT MATCHED THEN INSERT ROW WHEN MATCHED THEN 
UPDATE 
SET 
	A.Notes = B.Note, 
	A.Last_Update = B.Last_Update;